---
api_image_name: littlehawk03/api
api_container_name: api
lb_image_name: nginx
lb_image_tag: 1.23.4-alpine-slim
lb_container_name: lb_api

# api_image_tag: latest

FLUENTD_HOST: "192.168.89.107"
MONGO_HOST: "192.168.89.114"
MONGO_PORT: "27017"
FLASK_ENV: development