global:
  external_labels:
    username: annd
scrape_configs:
- job_name: cadvisor
  scrape_interval: 5s
  static_configs:
    - targets:
      - annd_cad:8080
- job_name: node
  scrape_interval: 5s
  static_configs:
    - targets: 
      - annd_exporter:9100
- job_name: 'prometheus'
  scrape_interval: 1m
  static_configs:
    - targets: 
      - localhost:9090
        #remote_write:
        #- url: 'http://171.236.38.100:9090/api/v1/write'
remote_write:
  - url: 'http://27.66.108.93:9090/api/v1/write'
