---
- name: Remove directory {{ db_dest }}
  ansible.builtin.file:
    path: "{{ db_dest }}"
    state: absent
  when: db_dest_cleanup | default(false) | bool

- name: Create directory {{ db_dest }}
  ansible.builtin.file:
    path: "{{ db_dest }}"
    state: directory
    mode: "0755"

- name: Copy files to {{ db_dest }}
  ansible.builtin.copy:
    src: ./
    dest: "{{ db_dest }}"
    mode: "0644"

- name: Generate docker-compose.yml
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ db_dest }}/docker-compose.yml"
    mode: "0644"

- name: Create and start service {{ db_service }}
  community.docker.docker_compose:
    project_src: "{{ db_dest }}"
    state: present
    services:
      - "{{ db_service }}"
