[host]
localhost ansible_connection=local

[nodes]
ec2-52-91-70-187.compute-1.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=./demo.pem
ec2-44-201-231-16.compute-1.amazonaws.com ansible_ssh_user=ubuntu ansible_ssh_private_key_file=./demo.pem