---
- name: Build lb image
  community.docker.docker_image:
    name: lb_image
    build:
      path: ./roles/lb/files
    source: build
    force_source: true

- name: Run lb container
  community.docker.docker_container:
    name: lb
    image: lb_image
    restart_policy: "unless-stopped"
    ports:
      - "3000:3000"
    networks:
      - name: network
    log_driver: fluentd
    log_options:
      fluentd-address: localhost:24224
      tag: lb
    