---
- name: Remove directory {{ lb_dest }}
  ansible.builtin.file:
    path: "{{ lb_dest }}"
    state: absent
  when: lb_dest_cleanup | default(false) | bool

- name: Ensure having directory {{ lb_dest }}
  ansible.builtin.file:
    path: "{{ lb_dest }}"
    state: directory
    mode: "0755"

- name: Generate nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "{{ lb_dest }}/nginx.conf"
    mode: "0644"

- name: Create and (re)start service {{ lb_service }}
  community.docker.docker_compose:
    project_src: "{{ lb_target_dest }}"
    state: present
    restarted: true
    services:
      - "{{ lb_service }}"

- name: Scale service {{ lb_target }} to {{ lb_target_scale }}
  community.docker.docker_compose:
    project_src: "{{ lb_target_dest }}"
    scale: "{ '{{ lb_target }}': '{{ lb_target_scale }}' }"
