version: '3.9'

services:
  react:
    build: frontend
    container_name: presentation_tier
    hostname: react
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "3000:3000"
    links:
      - fastapi

  fastapi:
    build: backend
    container_name: logic_tier
    restart: unless-stopped
    platform: linux/arm64
    ports:
      - "80:80"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: data_tier
    restart: unless-stopped
    hostname: mongodb
    environment:
      - MONGO_INITDB_DATABASE=vdt2023
    ports:
      - "27017:27017"
