- name: Install Docker Engine, containerd, and Docker Compose
  apt:
      name:
          [
              "docker-ce",
              "docker-ce-cli",
              "containerd.io",
              "docker-buildx-plugin",
              "docker-compose-plugin",
          ]
      state: present
  become: yes
  tags: docker
- name: Manage Docker as a non-root user
  user:
      name: hoangnd
      groups: docker
      append: yes
  become: yes
  tags: docker
