- name: Run docker image hoangndst/vdt-frontend:latest
  docker_container:
    name: frontend
    image: hoangndst/vdt-frontend:latest
    restart_policy: unless-stopped
    networks:
      - name: "{{ NETWORK_NAME }}"
    hostname: frontend
    ports:
      - "3000:80"
  become: yes
  tags: docker
