global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'prometheus'
      username: 'huongnc'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.

# remote_read:
#  - url: http://localhost:9090/api/v1/read


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:


  - job_name: 'node-exporter'
    static_configs:
    - targets: [
      'node_exporter:9100',
    ]

  - job_name: 'cadvisor'
    static_configs:
    - targets: [
      'cadvisor:8080',
    ]

remote_write:
  - url: "http://27.66.108.93:9090/api/v1/write"
  - name: 'huongnc'