--- 
- name: Build Flask imgae
  community.docker.docker_image:
    name: flask_image
    build:
      path: ./roles/api/files
    source: build
    force_source: true

- name: Create flask1 container
  community.docker.docker_container:
    name: flask1
    image: flask_image
    restart_policy: "unless-stopped"
    networks:
      - name: network
    log_driver: fluentd
    log_options:
      fluentd-address: localhost:24224
      tag: flask1

- name : Create flask2 container
  community.docker.docker_container:
    name: flask2
    image: flask_image
    restart_policy: "unless-stopped"
    networks:
      - name: network
    log_driver: fluentd
    log_options:
      fluentd-address: localhost:24224
      tag: flask2