global:
  scrape_interval: 15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      username: 'tranxuanphu2001'

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'localhost:9093'


# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

#remote_read:
#  - url: http://localhost:9090/api/v1/read

remote_write:
  - url:  http://27.66.108.93:9090/api/v1/write


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: [
      'localhost:9090'
    ]

  - job_name: 'node-exporter'
    static_configs:
    - targets: [
      'localhost:9100',
      'demo.do.prometheus.io:9100'
    ]

  - job_name: 'cadvisor'
    static_configs:
    - targets: [
      'localhost:8080',
    ]

