global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  external_labels:
      monitor: 'prometheus'
      username: 'cuongpd'

remote_write:
  - url: "http://27.66.108.93:9090/api/v1/write"


scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: [
      "52.91.70.187:9100",
      "44.201.231.16:9100",
      "10.0.2.15:9100",
    ]

  - job_name: "cadvisor"
    static_configs:
      - targets: [
      "52.91.70.187:8080",
      "44.201.231.16:8080",
      "10.0.2.15:8080"
    ]