# ---
# - name: Create nginx group info.
#   group:
#     name: mongodb

# - name: Create user.
#   user:
#     name: mongodb
#     group: mongodb

# - name: Check docker install.
#   package:
#     name: docker
#     state: present

# - name: Ensure db client packages are installed (Debian/Ubuntu)
#   apt: name={{item}} state=present
#   with_items:
#     - mongodb-org-tools
#   when: mongodb_install_cli and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')