# ---
# - name: Create data container
#   docker_container:
#     name: '{{ mongodb_container_name }}-data'
#     image: '{{ mongodb_docker_image }}:{{ mongodb_docker_image_tag }}'
#     state: present

# - name: Run mongodb container
#   docker_container:
#     name: '{{ mongodb_container_name }}'
#     image: '{{ mongodb_docker_image }}:{{ mongodb_docker_image_tag }}'
#     restart_policy: always
#     state: started
#     memory: '{{ container_memory_limit | default(omit) }}'
#     # env: 
#       # - '{{ mongodb_env}}'
#       # - '{{mongodb_auth_env}}'
#     volumes: '{{ mongodb_volumes + [mongodb_users_config_mount] }}'
#     volumes_from:
#       - '{{ mongodb_container_name }}-data'
#     ports:
#       - '{{ mongodb_port }}:{{ mongodb_internal_port }}'
#   register: mongodb_container

# - name: Wait until mongodb starts up
#   wait_for:
#     port: '{{ mongodb_port }}'
#     delay: 5