- name: Check network
  docker_network_info:
    name: monitor
  register: docker_network
  become: yes
  tags: docker

- name: Create docker network
  docker_network:
    name: monitor
  when: docker_network.exists == false
  register: docker_network
  become: yes
  tags: docker

- name: Run cadvisor container
  docker_container:
    image: gcr.io/cadvisor/cadvisor
    name: cadvisor
    ports:
      - 8080:8080
    networks:
      - name: monitor
    volumes:
      - /:/tmp/rootfs:ro
      - /var/tmp/run:/var/run:rw
      - /sys:/tmp/sys:ro
      - /var/tmp/lib/docker/:/var/lib/docker:ro

- name: Run node exporter container
  docker_container:
    image: prom/node-exporter
    name: node-exporter
    networks:
      - name: monitor
    ports:
      - 9100:9100
    restart_policy: "unless-stopped"
    volumes:
      - /proc:/tmp/host/proc:ro
      - /sys:/tmp/host/sys:ro
      - /:/tmp/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'


- name: Copy prometheus config
  copy:
    src: ./roles/monitor/files/prometheus.yaml
    dest: /tmp
  become: yes

- name: Run Prometheus container
  docker_container:
    image: prom/prometheus
    name: prometheus
    networks:
      - name: monitor
    restart_policy: "unless-stopped"
    volumes: /tmp/10.gk/prometheus.yaml:/etc/prometheus/prometheus.yaml
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml