---
all:
  hosts:
    localhost:
      ansible_password: 207987
      ansible_sudo_pass: 207987
      ansible_python_interpreter: /usr/bin/python3

    node1:
      ansible_host: 192.168.40.134
      ansible_python_interpreter: /usr/bin/python3
      ansible_user: ubuntu4
      ansible_password: 207987
      ansible_sudo_pass: 207987
