---
- name: Build nginx image
  community.docker.docker_image:
    name: nginx_image
    build:
      path: ./roles/web/files
      dockerfile: Dockerfile
    source: build
    force_source: true


- name: Create web1 container
  community.docker.docker_container:
    name: nginx1
    image: nginx_image
    restart_policy: "unless-stopped"
    ports:
      - "81:81"
    networks:
      - name: network
    log_driver: fluentd
    log_options:
      fluentd-address: localhost:24224
      tag: nginx1


- name: Create web2 container
  community.docker.docker_container:
    name: nginx2
    image: nginx_image
    restart_policy: "unless-stopped"
    ports:
      - "82:82"
    networks:
      - name: network
    log_driver: fluentd
    log_options:
      fluentd-address: localhost:24224
      tag: nginx2
