---
network_name: vdt2023

mysql_container_name: mysql-vdt2023
backend_container_name: backend-vdt2023
frontend_container_name: frontend-vdt2023
nginx_container_name: nginx-vdt2023

password_vaulted: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34646661653261313661313765363136353038666638363064303364636530356436663565316133
          3135623135633063626263343835353262646335376462630a626662663163346433633366316130
          39376438343638633361656130616461323238333530316337616330663364326134363066343663
          3666323037376661610a646637333134316364303362646133313963393439353838316464316434
          6234

ip_ubuntu01: 34.87.138.166
ip_ubuntu02: 35.247.130.29
ip_ubuntu03: 34.87.140.197
ip_ubuntu04: 34.124.148.72
ip_ubuntu05: 34.92.112.202
ip_ubuntu06: 34.92.110.53

python_path: /usr/bin/python3
