---
- name: Run cadvisor container
  community.docker.docker_container:
    image: gcr.io/cadvisor/cadvisor
    name: cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    networks:
      - name: network
    
- name: Run node exporter container
  community.docker.docker_container:
    image: prom/node-exporter
    name: node-exporter
    restart_policy: "unless-stopped"
    ports:
      - 9100:9100
    networks: 
      - name: network
      
- name: Run Prometheus container
  community.docker.docker_container:
    name: prometheus
    image: prom/prometheus
    restart: true
    published_ports: "9090:9090"
    volumes:
      - "./roles/monitor/files/prometheus.yaml:/etc/prometheus/prometheus.yaml"    
    networks: 
      - name: network