name: CD

on:
  create:
    tags:
      - '*'

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      - name: Build and push flask
        uses: docker/build-push-action@v4
        with:
          context: 10.Midterm/Docker/app
          file: 10.Midterm/Docker/app/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flask:latest

      - name: Build and push nginx
        uses: docker/build-push-action@v4
        with:
          context: 10.Midterm/Docker/nginx
          file: 10.Midterm/Docker/nginx/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/nginx:latest