name: cd-build-push-on-tag

on:
    push:
      tags:
        - 'v[0-9]+.[0-9]+.[0-9]+'
        # - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push api server
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ducpa01/python-buddy:${{github.ref_name}}
          context: "{{defaultContext}}:src/app"

      - name: Build and push nginx webserver
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ducpa01/nginx-buddy:${{github.ref_name}}
          context: "{{defaultContext}}:src/nginx"
