name: Unit test

on:
  pull_request:
    branches:
      - main
      
  push:
    branches:
      - 3_Midterm

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r Midterm1/roles/api/files/requirements.txt

      - name: Check PEP8 compliance
        run: pycodestyle --ignore=W504,E501,E275 Midterm1/roles/api/files/app.py

      - name: Run container
        run: |
          docker network create network
          docker build -t db_image Midterm1/roles/db/files
          docker run -d --name db --network network db_image
          docker build -t flask_image Midterm1/roles/api/files
          docker run -d --name flask --network network flask_image
          docker build -t nginx_image Midterm1/roles/web/files
          docker run -d -p 81:81 --name nginx --link flask1:flask1 --network network nginx_image

      - name: Run Unit Test
        run: python Midterm1/roles/api/files/unit_test.py